// App Types
export const DOWNLOAD_IMAGE = "DOWNLOAD_IMAGE";
export const DOWNLOADED_IMAGE = "DOWNLOADED_IMAGE";

// Service Types
export const GET_IMAGE_LIST = "GET_IMAGE_LIST";
export const GET_IMAGE_LIST_SUCCESS = "GET_IMAGE_LIST_SUCCESS";
export const GET_IMAGE_LIST_FAIL = "GET_IMAGE_LIST_FAIL";
export const GET_SEARCH_IMAGE_LIST = "GET_SEARCH_IMAGE_LIST";
export const GET_SEARCH_IMAGE_LIST_SUCCESS = "GET_SEARCH_IMAGE_LIST_SUCCESS";
export const GET_SEARCH_IMAGE_LIST_FAIL = "GET_SEARCH_IMAGE_LIST_FAIL";
